### ISSUE TITLE
Word embedding issue

### ISSUE THREAD

**Issue by uqzhichen** [CSC2548/text2image2textGAN#1]
Hi Junwei, I'm wondering if you are willing to make the word embedding code of the dataset public?

**Comment by satyakrishnagorti** [comment]
Hi Simon, I am sorry we couldn't document this well. There is a script convert_flowers_to_hd5_script.py that converts the text of flowers data set to skipthought embeddings and a similar script for the birds data set. This script depends on package https://github.com/Cadene/skip-thoughts.torch/tree/master/pytorch. You can get the flower and bird dataset by following https://github.com/reedscot/icml2016

**Comment by uqzhichen** [comment]
Thank you so much Satya

**Comment by dany87kuo** [comment]
@uqzhichen  Do you solve it?  I have the same question right now.
Could you help me?  Thanks!
