### ISSUE TITLE
cvpr2016_cub dataset

### ISSUE THREAD

**Issue by billamiable** [CSC2548/text2image2textGAN#2]
Hi, I wanna try your method and when I looked at the config.yaml file, there are paths related to name that is "cvpr2016_cub". I am relatively new to this area, and I only see "CUB_200_2011" dataset at http://www.vision.caltech.edu/visipedia/CUB-200-2011.html. Are they the same? Thanks!

**Comment by satyakrishnagorti** [comment]
HI @billamiable, the dataset can be found here https://drive.google.com/file/d/0B0ywwgffWnLLZW9uVHNjb2JmNlE/view.
More details can be found here: https://github.com/reedscot/cvpr2016

**Comment by billamiable** [comment]
Hi, I am getting confused about the pipeline of running your code. Do you mind to give a guideline of how to run the code? Really appreciate that! @satyakrishnagorti

**Comment by dany87kuo** [comment]
@billamiable Do you know the pipeline of this code?
