### ISSUE TITLE
KeyError: 'img'

### ISSUE THREAD

**Issue by dany87kuo** [CSC2548/text2image2textGAN#7]
I run convert_birds_to_skipthought_hd5_script.py,But get error:KeyError: 'img'
How do you solve it? Thanks for your help~

![Screenshot from 2021-05-26 10-01-11](https://user-images.githubusercontent.com/84573235/119673475-609fca80-be09-11eb-98c8-1d89232d117e.png)

**Comment by abhineet99** [comment]
You can look at setup_env.txt in my forked version of this repo, which should help with possible other issues too. https://github.com/abhineet99/text2image2textGAN
